### ISSUE TITLE
PEQ Editor integration - stops reporting on month change (new log file)

### ISSUE THREAD

**Issue by projecteon** [xackery/talkeq#12]
At each month change the peq editor starts writing to a new log file. It doesnt seem that TalkEQ picks up this change and requires a restart every month. Possible to get this fixed?

**Comment by xackery** [comment]
746a2d19bd709ff242a02fc486e8f4f2656d518a may fix this

**Comment by xackery** [comment]
Closing, we can create a new or reopen if new issues pop up next month
