### ISSUE TITLE
Bot is cutting last character off of text 

### ISSUE THREAD

**Issue by splose** [xackery/talkeq#5]
Hey I just downloaded this last night and found that the bot seems to be cutting off the last character

ingame/discord:

![1593ef7017163c40ea3abaa0501da757](https://user-images.githubusercontent.com/4369261/113500689-0c095e80-94ee-11eb-9a45-430274c9de4d.png)

Bot Debug:

![8eaf2e00451edc847c6d9496c736004d](https://user-images.githubusercontent.com/4369261/113500712-3b1fd000-94ee-11eb-93e7-663dd27788c6.png)

**Comment by splose** [comment]
Actually had legacy telnet on and that seemed to be the issue.. Can probably disregard this.

**Comment by xackery** [comment]
Right on, yeah legacy telnet was for older eqemu telnet doing a truncation thingie, so the clipped message makes sense as source.
