### ISSUE TITLE
send with webhook instead of bot for masked links

### ISSUE THREAD

**Issue by catapultam-habeo** [xackery/talkeq#9]
```go
//telnet_msg.go

// replace the relevant line with
out += fmt.Sprintf("[%s](%s%d)", itemName, t.config.ItemURL, itemID)
```

```go
// discord.go
// add to import block ...
	"net/http"
	"encoding/json"
//done import block ...

// Send sends a message to discord
func (t *Discord) Send(req request.DiscordSend) error {
	if !t.config.IsEnabled {
		return fmt.Errorf("not enabled")
	}

	if !t.isConnected {
		return fmt.Errorf("not connected")
	}

	webhookUrl := //<YOUR WEBHOOK URL>

	payload := DiscordWebhook{
		Content: req.Message,
	}

	jsonPayload, err := json.Marshal(payload)
	if err != nil {
		return fmt.Errorf("Failed to parse payload to JSON: %w", err)
	}

	resp, err := http.Post(webhookUrl, "application/json", bytes.NewBuffer(jsonPayload))
	if err != nil {
		return fmt.Errorf("Failed to send POST request: %w", err)
	}

	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("Received non-200 response: %d", resp.StatusCode)
	}

	return nil
}
```

My Go knowledge is absolute garbage and I have no idea how to integrate this correctly into your overall structure (my fork is getting more and more off the rails and is not-good-but-works-for-my-needs), so not gonna PR it. This does work, though. Maybe useful to you or someone else.

I'm going to try to work in reverse link handling (convert allaclone links to ingame links), and would love to contribute all of this but would need some handholding on getting it together correctly.

**Comment by catapultam-habeo** [comment]
Closing this. I'll do this as a PR when I'm not drunk.

**Comment by xackery** [comment]
I'm.. a bit confused, is the goal with this to use the eqemu API server webhook because item links get converted?

**Comment by xackery** [comment]
If so, we can just feature request dev team for telnet to support markdown itemlinks, too, on emote world, to get feature parity with the eqemu API.

**Comment by catapultam-habeo** [comment]
No, this uses a [discord webhook](https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks). For whatever reason, Bots & Users can't send what they call 'masked links' and the rest of the world calls 'hyperlinks', but webhooks can. eqemu supports webhooks natively, and so you can just send that markdown through a perl script or w\e, but it doesn't work through talkeq without this change.

This is the kind of result you can get, which, IMHO, is much nicer than the raw link.

![image](https://github.com/xackery/talkeq/assets/97849758/81a20634-318f-472c-9f07-b5ba7218f503)

What I posted above really is just a quick and dirty hack. I've also done some work on in-game claiming of discord handles (so no roles etc) and support for 64-bit itemlinks. When I get reverse parsing of links working I'll clean everything up and submit a PR(s) depending on which of those features you want in main or not. Or if you don't want them at all I'll skip it. 

Apologies for posting this half-cocked last night.

**Comment by xackery** [comment]
Aha, I see. I saw this posting on discordgo's discord:
<img width="667" alt="Screen Shot 2023-06-30 at 6 56 28 AM" src="https://github.com/xackery/talkeq/assets/845670/cd98a7c3-4987-482f-bd76-efc627740858">

link: https://support.discord.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline-

It's possible this will roll out to bots, too. This may be worth waiting instead of requiring folks to configure eqemu's discord integration as a dependency for talkeq

**Comment by catapultam-habeo** [comment]
This doesn't use eqemu's discord integration at all. It does require an additional config step for talkeq, and the webhook can be reused for eqemu if desired.

What I posted is insecure, because the secret is dangled there in plaintext and doesn't use a config file, but that is a relatively trivial improvement.

It could also be an optional config... Either way, I don't expect or request action from you on this.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by xackery** [comment]
Will the link I note resolve it though, if it's rolled out to all guilds? Seems they're planning to add masked links to all users and probably bots in the next short while.

**Comment by catapultam-habeo** [comment]
Yes, probably? They've already rolled it out and reverted it once though fwiw.

Sent from Proton Mail mobile

-------- Original Message --------
